### PR TITLE
feat: Support for bus interfaces

### PR DESCRIPTION
**Pull request by ZimGil**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: link is broken ~~https://github.com/nestjs-architect/typed-cqrs/blob/master/CONTRIBUTING.md#git-guidelines~~
- [X] Tests for the changes have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #5

## What is the new behavior?
Working with the interfaces as well

## Does this PR introduce a breaking change?

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by ZimGil** [comment]
@Sikora00 Care to review please? :)

**Comment by Sikora00** [comment]
Oh, I just noticed this. Looks fine in the first look. I will proceed by Friday

**Comment by Sikora00** [comment]
@ZimGil what about supporting queries and commands that don't extend our classes? 
We should keep supporting base capabilities so adding this package in the middle of a project is not a pain.

Out of curiosity, what use case do you have to use someone's (nestjs/cqrs) interface?

**Review by Sikora00 — CHANGES_REQUESTED** [review]
@ZimGil what about supporting queries and commands that don't extend our classes?
We should keep supporting base capabilities so adding this package in the middle of a project is not a pain.

**Comment by Sikora00** [comment]
In fact. it is a completely new interface, so what's wrong with keeping it separate from the Nest's one?

**Comment by ZimGil** [comment]
@Sikora00 I'll explain the use case first,

We're using both [nestjs/cqrs](https://github.com/nestjs/cqrs) and [Papooch/nestjs-cls](https://github.com/Papooch)

This combination causes an issue in scale as events may be handled with the wrong CLS store so we had to come in with a wrapper for the default pubsub and the default eventBus.

Now we're using the exact same interface, but a different injection token.

Ideally we'd like to avoid needing to import bus interfaces from a different package as this is all happening in our CQRS module and nothing is different for the consumer except for the injection token.

Theoretically we could have dedicated bus interface but it seems redundant when we've already had used [typed-cqrs](https://github.com/nestjs-architects/typed-cqrs) to override the bus classes

Isn't that the purpose of this package?

**Pull request merged**
